# Generated by Django 3.2.4 on 2021-06-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmodule',
            name='module_name',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
