# Generated by Django 3.2.4 on 2021-06-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_auto_20210622_1426"),
        ("participant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="course",
        ),
        migrations.AddField(
            model_name="participant",
            name="course",
            field=models.ManyToManyField(to="course.Course"),
        ),
    ]
