# Generated by Django 3.2.4 on 2021-06-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_auto_20210623_1422"),
        ("participant", "0002_auto_20210622_1426"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="course",
        ),
        migrations.AddField(
            model_name="participant",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.course",
            ),
        ),
    ]
