# Generated by Django 3.2.4 on 2021-06-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_alter_participant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
