# Generated by Django 3.2.4 on 2021-06-22 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolmodule", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0002_auto_20210622_1349"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="school_module",
        ),
        migrations.AddField(
            model_name="course",
            name="school_module",
            field=models.ManyToManyField(to="schoolmodule.SchoolModule"),
        ),
        migrations.RemoveField(
            model_name="course",
            name="teacher",
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
