# Generated by Django 3.2.4 on 2021-06-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
