# Generated by Django 3.2.4 on 2021-06-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_course_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.CharField(default='https://discord.gg/', max_length=255),
        ),
    ]
