# Generated by Django 3.2.4 on 2021-06-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_rename_link_course_link_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='link_to',
            new_name='link',
        ),
    ]
