# Generated by Django 3.2.4 on 2021-06-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_rename_link_course_link_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link_to',
            field=models.CharField(blank=True, default='https://discord.gg/', max_length=255, null=True),
        ),
    ]
